# Generated by Django 5.1.2 on 2024-12-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_image_remove_comment_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.post'),
        ),
        migrations.DeleteModel(
            name='CommentMedia',
        ),
    ]
