# Generated by Django 5.1.2 on 2024-12-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_message_is_read_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
